# Generated by Django 5.1.4 on 2025-01-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blog_section_alter_blog_status_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Popular', 'Popular'), ('Recent', 'Recent')], max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], default=0, max_length=1),
        ),
    ]
