# Generated by Django 5.1.4 on 2025-01-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog_author_email_alter_blog_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Popular', 'Popular'), ('Recent', 'Recent')], max_length=100),
        ),
    ]
